-- SQL Script para Oracle Cloud con Wallet

-- 1. Tabla ELEFANTES
CREATE TABLE ELEFANTES (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    EDAD NUMBER,
    HABITAT VARCHAR2(100),
    ZONA_ORIGEN VARCHAR2(100),
    PESO NUMBER,
    TAMANO NUMBER,
    ALTURA NUMBER,
    GENERO VARCHAR2(20),
    PERIODO_GESTACION NUMBER,
    TIPO_PELAJE VARCHAR2(100),
    LACTANCIA NUMBER,
    TAM_OREJA_IZQ NUMBER,
    TAM_OREJA_DER NUMBER,
    TAM_COLMILLO_IZQ NUMBER,
    TAM_COLMILLO_DER NUMBER,
    TAM_TROMPA NUMBER
);

-- 2. Tabla LEONES
CREATE TABLE LEONES (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    EDAD NUMBER,
    HABITAT VARCHAR2(100),
    ZONA_ORIGEN VARCHAR2(100),
    PESO NUMBER,
    TAMANO NUMBER,
    ALTURA NUMBER,
    GENERO VARCHAR2(20),
    PERIODO_GESTACION NUMBER,
    TIPO_PELAJE VARCHAR2(100),
    LACTANCIA NUMBER,
    TAM_MELENA NUMBER,     -- Atributo específico de León
    DECIBELES_RUGIDO NUMBER, -- Atributo específico de León
    ES_ALFA CHAR(1)        -- 'S' o 'N'
);

COMMIT;
